package org.xson.core.reader;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.Inet4Address;
import java.net.Inet6Address;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.URI;
import java.net.URL;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Currency;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TimeZone;
import java.util.UUID;
import org.xson.core.ReaderModel;
import org.xson.core.XsonReader;
import org.xson.core.testmodel.XUser7;

public class FullTypeBeanReader implements XsonReader {
	public Object read(ReaderModel paramReaderModel) {
		XUser7 localXUser7 = new XUser7();
		paramReaderModel.appendObject(localXUser7);
		localXUser7.setB1((Byte) paramReaderModel.getObject());
		localXUser7.setB2((Boolean) paramReaderModel.getObject());
		localXUser7.setAd((InetAddress) paramReaderModel.getObject());
		localXUser7.setAd4((Inet4Address) paramReaderModel.getObject());
		localXUser7.setAd6((Inet6Address) paramReaderModel.getObject());
		localXUser7.setArr1((byte[]) paramReaderModel.getObject());
		localXUser7.setArr2((short[]) paramReaderModel.getObject());
		localXUser7.setArr3((boolean[]) paramReaderModel.getObject());
		localXUser7.setArr4((char[]) paramReaderModel.getObject());
		localXUser7.setArr5((int[]) paramReaderModel.getObject());
		localXUser7.setArr51((int[][]) paramReaderModel.getObject());
		localXUser7.setArr52((int[][][]) paramReaderModel.getObject());
		localXUser7.setArr6((long[]) paramReaderModel.getObject());
		localXUser7.setArr7((float[]) paramReaderModel.getObject());
		localXUser7.setArr8((double[]) paramReaderModel.getObject());
		localXUser7.setB3((Short) paramReaderModel.getObject());
		localXUser7.setB4((Character) paramReaderModel.getObject());
		localXUser7.setB5((Integer) paramReaderModel.getObject());
		localXUser7.setB51((Integer) paramReaderModel.getObject());
		localXUser7.setB6((Long) paramReaderModel.getObject());
		localXUser7.setB7((Float) paramReaderModel.getObject());
		localXUser7.setB8((Double) paramReaderModel.getObject());
		localXUser7.setBi((BigInteger) paramReaderModel.getObject());
		localXUser7.setCls((Class) paramReaderModel.getObject());
		localXUser7.setCu((Currency) paramReaderModel.getObject());
		localXUser7.setD1((java.util.Date) paramReaderModel.getObject());
		localXUser7.setD2((java.sql.Date) paramReaderModel.getObject());
		localXUser7.setD3((Time) paramReaderModel.getObject());
		localXUser7.setD4((Timestamp) paramReaderModel.getObject());
		localXUser7.setDi((BigDecimal) paramReaderModel.getObject());
		localXUser7.setIsad((InetSocketAddress) paramReaderModel.getObject());
		localXUser7.setList((List) paramReaderModel.getObject());
		localXUser7.setLo((Locale) paramReaderModel.getObject());
		localXUser7.setMap((Map) paramReaderModel.getObject());
		localXUser7.setName((String) paramReaderModel.getObject());
		localXUser7.setName1((String) paramReaderModel.getObject());
		localXUser7.setS((Integer) paramReaderModel.getObject());
		localXUser7.setSb1((StringBuffer) paramReaderModel.getObject());
		localXUser7.setSb2((StringBuilder) paramReaderModel.getObject());
		localXUser7.setTz((TimeZone) paramReaderModel.getObject());
		localXUser7.setU1((URI) paramReaderModel.getObject());
		localXUser7.setU2((URL) paramReaderModel.getObject());
		localXUser7.setUu((UUID) paramReaderModel.getObject());
		localXUser7.setV1(paramReaderModel.getByte());
		localXUser7.setV2(paramReaderModel.getShort());
		localXUser7.setV3(paramReaderModel.getInt());
		localXUser7.setV4(paramReaderModel.getLong());
		localXUser7.setV5(paramReaderModel.getFloat());
		localXUser7.setV6(paramReaderModel.getDouble());
		localXUser7.setV7(paramReaderModel.getBoolean());
		localXUser7.setV8(paramReaderModel.getChar());
		return localXUser7;
	}
}